
{{ config(materialized='table') }}

SELECT
    ROW_NUMBER() OVER () as id,
    レコード区分 as is_first,
    回収分類 as answer_type,
    バッチ番号 as id_batch,
    整理番号：市区町村 as id_area,
    整理番号：ロット番号 as id_lot,
    整理番号：世帯ＳＱ as id_household,
    世帯人数／5歳未満含む as household_size,
    世帯人数／5歳未満除く as household_size_over_5th,
    回収個人票数 as individual,
    現住所：完全桁数 as address_accuracy,
    現住所：ゾーンコード as address_zcode,
    現住所：番・番地 as address_block,
    現住所：号 as address_number,
    現住所：緯度 as address_lat,
    現住所：経度 as address_lon,
    現住所：マッチングレベル as address_level,
    現住所：JISコード（5桁） as address_jcode,
    個人番号 as personal_number,
    勤務先・通学先・通園先：完全桁数 as office_accuracy,
    勤務先・通学先・通園先：ゾーンコード as office_zcode,
    勤務先・通学先・通園先：番・番地 as office_block,
    勤務先・通学先・通園先：号 as office_number,
    勤務先・通学先・通園先：緯度 as office_lat,
    勤務先・通学先・通園先：経度 as office_lon,
    勤務先・通学先・通園先：マッチングレベル office_level,
    勤務先・通学先・通園先：JISコード（5桁） as office_jcode,
    トリップの有無 as is_trip,
    トリップ数 as trip_total,
    トリップ番号 as trip_number,
    出発地：区分 as origin_type,
    出発地：完全桁数 as origin_accuracy,
    出発地：ゾーンコード as origin_zcode,
    出発地：番・番地 as origin_block,
    出発地：号 as origin_number,
    出発地：緯度 as origin_lat,
    出発地：経度 as origin_lon,
    出発地：マッチングレベル as origin_level,
    出発地：JISコード（5桁） as origin_jcode,
    到着地：区分 as destination_type,
    到着地：完全桁数 as destination_accuracy,
    到着地：ゾーンコード as destination_zcode,
    到着地：番・番地 as destination_block,
    到着地：号 as destination_number,
    到着地：緯度 as destination_lat,
    到着地：経度 as destination_lon,
    到着地：マッチングレベル as destination_level,
    到着地：JISコード（5桁） as destination_jcode,
FROM read_csv_auto('/Users/nagampere/File/horkew/projects/tokyo2018/sources/MS2711_UTF.csv')
