SELECT
    id,
    pref_id as "都道府県ID",
    pref_name as "都道府県名",
    pref_id_name as "都道府県ID名",
    section_id as "部門ID",
    section_name as "部門名",
    section_id_name as "部門ID名",
    year as "年",
    value_added_real as "実質付加価値",
    value_added_nominal as "名目付加価値",
    real_capital_stock as "実質純資本ストック(知財除く)",
    cost_of_capital as "名目資本サービス(知財除く)",
    quality_of_capital as "資本の質指数(知財除く)",
    real_capital_stock_patent as "実質純資本ストック(知財)",
    cost_of_capital_patent as "名目資本サービス(知財)",
    quality_of_capital_patent as "資本の質指数(知財)",
    man_hour as "総労働時間",
    cost_of_labor as "名目労働コスト",
    quality_of_labor_index as "労働の質指数",
    quality_of_labor_comparison_index as "労働の質格差指数",
    number_of_employed_persons as "就業者数",
    TFP as "TFP",
    delta_VA as "実質付加価値成長率",
    delta_Z as "実質資本ストック寄与率(知財除く)",
    delta_QK as "資本の質寄与率(知財除く)",
    delta_Z_patent as "実質資本ストック寄与率(知財)",
    delta_QK_patent as "資本の質寄与率(知財)",
    delta_H as "マンアワー寄与率",
    delta_QL as "労働の質寄与率",
    labor_productivity_growth as "労働生産性成長率",
    capital_stock_growth as "資本装備率成長率(知財除く)",
    capital_stock_patent_growth as "資本装備率成長率(知財)",
    quality_of_capital_growth as "資本の質成長率(知財除く)",
    quality_of_capital_patent_growth as "資本の質成長率(知財)",
    quality_of_labor_growth as "労働の質成長率",
    cost_of_capital_share as "資本コストシェア(知財除く)",
    cost_of_capital_patent_share as "資本コストシェア(知財)",
    RTFP as "相対TFP",
    value_added_share as "産業別名目付加価値シェア",
FROM {{ref('mrt_all')}} 
ORDER BY "都道府県ID", "部門ID", "年"
