SELECT
    int_capital__indices_of_capital_input_by_sector.id as id,
    int_capital__indices_of_capital_input_by_sector.section_id as section_id,
    int_capital__indices_of_capital_input_by_sector.section_name as section_name,
    int_capital__indices_of_capital_input_by_sector.year as year,
    int_capital__nominal_investment_by_sector.nominal_investment as nominal_investment,
    int_capital__real_investment_by_sector.real_investment as real_investment,
    int_capital__indices_of_capital_input_by_sector.input_index as input_index,
    int_capital__indices_of_capital_quality_by_sector.quality_index as quality_index,
    int_capital__nominal_net_capital_stock_by_sector.nominal_net_stock as nominal_net_stock,
    int_capital__real_net_capital_stock_by_sector.real_net_stock as real_net_stock,
    int_capital__nominal_capital_cost_by_sector.nominal_cost as nominal_cost,
    int_capital__investment_stock_matrix_by_sector.RS_nominal_investment as RS_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.RS_real_investment as RS_real_investment,
    int_capital__investment_stock_matrix_by_sector.RS_nominal_capital_stock as RS_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.RS_real_capital_stock as RS_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.RS_nominal_capital_cost as RS_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.NRS_nominal_investment as NRS_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.NRS_real_investment as NRS_real_investment,
    int_capital__investment_stock_matrix_by_sector.NRS_nominal_capital_stock as NRS_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.NRS_real_capital_stock as NRS_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.NRS_nominal_capital_cost as NRS_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.ST_nominal_investment as ST_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.ST_real_investment as ST_real_investment,
    int_capital__investment_stock_matrix_by_sector.ST_nominal_capital_stock as ST_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.ST_real_capital_stock as ST_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.ST_nominal_capital_cost as ST_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.LA_nominal_investment as LA_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.LA_real_investment as LA_real_investment,
    int_capital__investment_stock_matrix_by_sector.LA_nominal_capital_stock as LA_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.LA_real_capital_stock as LA_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.LA_nominal_capital_cost as LA_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.TE_nominal_investment as TE_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.TE_real_investment as TE_real_investment,
    int_capital__investment_stock_matrix_by_sector.TE_nominal_capital_stock as TE_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.TE_real_capital_stock as TE_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.TE_nominal_capital_cost as TE_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.CPE_nominal_investment as CPE_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.CPE_real_investment as CPE_real_investment,
    int_capital__investment_stock_matrix_by_sector.CPE_nominal_capital_stock as CPE_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.CPE_real_capital_stock as CPE_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.CPE_nominal_capital_cost as CPE_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.CME_nominal_investment as CME_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.CME_real_investment as CME_real_investment,
    int_capital__investment_stock_matrix_by_sector.CME_nominal_capital_stock as CME_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.CME_real_capital_stock as CME_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.CME_nominal_capital_cost as CME_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.OE_nominal_investment as OE_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.OE_real_investment as OE_real_investment,
    int_capital__investment_stock_matrix_by_sector.OE_nominal_capital_stock as OE_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.OE_real_capital_stock as OE_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.OE_nominal_capital_cost as OE_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.DE_nominal_investment as DE_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.DE_real_investment as DE_real_investment,
    int_capital__investment_stock_matrix_by_sector.DE_nominal_capital_stock as DE_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.DE_real_capital_stock as DE_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.DE_nominal_capital_cost as DE_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.CA_nominal_investment as CA_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.CA_real_investment as CA_real_investment,
    int_capital__investment_stock_matrix_by_sector.CA_nominal_capital_stock as CA_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.CA_real_capital_stock as CA_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.CA_nominal_capital_cost as CA_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.RD_nominal_investment as RD_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.RD_real_investment as RD_real_investment,
    int_capital__investment_stock_matrix_by_sector.RD_nominal_capital_stock as RD_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.RD_real_capital_stock as RD_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.RD_nominal_capital_cost as RD_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.ME_nominal_investment as ME_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.ME_real_investment as ME_real_investment,
    int_capital__investment_stock_matrix_by_sector.ME_nominal_capital_stock as ME_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.ME_real_capital_stock as ME_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.ME_nominal_capital_cost as ME_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.CS_nominal_investment as CS_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.CS_real_investment as CS_real_investment,
    int_capital__investment_stock_matrix_by_sector.CS_nominal_capital_stock as CS_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.CS_real_capital_stock as CS_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.CS_nominal_capital_cost as CS_nominal_capital_cost,
    int_capital__investment_stock_matrix_by_sector.AO_nominal_investment as AO_nominal_investment,
    int_capital__investment_stock_matrix_by_sector.AO_real_investment as AO_real_investment,
    int_capital__investment_stock_matrix_by_sector.AO_nominal_capital_stock as AO_nominal_capital_stock,
    int_capital__investment_stock_matrix_by_sector.AO_real_capital_stock as AO_real_capital_stock,
    int_capital__investment_stock_matrix_by_sector.AO_nominal_capital_cost as AO_nominal_capital_cost
FROM
    {{ref('int_capital__indices_of_capital_input_by_sector')}} as int_capital__indices_of_capital_input_by_sector

LEFT JOIN
    {{ref('int_capital__nominal_investment_by_sector')}} as int_capital__nominal_investment_by_sector
    ON (int_capital__nominal_investment_by_sector.section_id = int_capital__indices_of_capital_input_by_sector.section_id)
    AND (int_capital__nominal_investment_by_sector.year = int_capital__indices_of_capital_input_by_sector.year)
LEFT JOIN
    {{ref('int_capital__real_investment_by_sector')}} as int_capital__real_investment_by_sector
    ON (int_capital__real_investment_by_sector.section_id = int_capital__indices_of_capital_input_by_sector.section_id)
    AND (int_capital__real_investment_by_sector.year = int_capital__indices_of_capital_input_by_sector.year)
LEFT JOIN
    {{ref('int_capital__indices_of_capital_quality_by_sector')}} as int_capital__indices_of_capital_quality_by_sector
    ON (int_capital__indices_of_capital_quality_by_sector.section_id = int_capital__indices_of_capital_input_by_sector.section_id)
    AND (int_capital__indices_of_capital_quality_by_sector.year = int_capital__indices_of_capital_input_by_sector.year)
LEFT JOIN
    {{ref('int_capital__nominal_net_capital_stock_by_sector')}} as int_capital__nominal_net_capital_stock_by_sector
    ON (int_capital__nominal_net_capital_stock_by_sector.section_id = int_capital__indices_of_capital_input_by_sector.section_id)
    AND (int_capital__nominal_net_capital_stock_by_sector.year = int_capital__indices_of_capital_input_by_sector.year)
LEFT JOIN
    {{ref('int_capital__real_net_capital_stock_by_sector')}} as int_capital__real_net_capital_stock_by_sector
    ON (int_capital__real_net_capital_stock_by_sector.section_id = int_capital__indices_of_capital_input_by_sector.section_id)
    AND (int_capital__real_net_capital_stock_by_sector.year = int_capital__indices_of_capital_input_by_sector.year)
LEFT JOIN
    {{ref('int_capital__nominal_capital_cost_by_sector')}} as int_capital__nominal_capital_cost_by_sector
    ON (int_capital__nominal_capital_cost_by_sector.section_id = int_capital__indices_of_capital_input_by_sector.section_id)
    AND (int_capital__nominal_capital_cost_by_sector.year = int_capital__indices_of_capital_input_by_sector.year)
LEFT JOIN
    {{ref('int_capital__investment_stock_matrix_by_sector')}} as int_capital__investment_stock_matrix_by_sector
    ON (int_capital__investment_stock_matrix_by_sector.section_id = int_capital__indices_of_capital_input_by_sector.section_id)
    AND (int_capital__investment_stock_matrix_by_sector.year = int_capital__indices_of_capital_input_by_sector.year)
ORDER BY id
