horkew:
  outputs:
    dev:
      type: duckdb
      path: catalog.duckdb
      threads: 1
      extentions: 
        - spatial
      plugins:
        - module: excel

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4
      extentions: 
        - spatial

  target: dev
