horkew:
  outputs:
    dev:
      type: duckdb
      path: catalog.duckdb
      threads: 1
      extensions: 
        - spatial

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4
      extensions: 
        - spatial

  target: dev
